global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Net;
global using System.Text;
global using System.Text.Json;
global using Quotebot.Data.Configuration;
global using Quotebot.Domain.Entities;
global using Quotebot.Data.Serialization;