name: Build

env:
  SLN_PATH: './src/Quotebot.sln'

on:
  pull_request:
    branches:
      - main
  push:
    branch:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Version
        run: |
          $version = "1.0.$([System.DateTime]::Now.ToString("yyMM")).$Env:GITHUB_RUN_ID"
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false
      - name: dotnet build
        run: dotnet build ${{ENV.SLN_PATH}} --configuration Debug /p:AssemblyVersion ${{ENV.BuildVersion}}
      