name: Build and Deploy Quotebot

env:
  BINARIES: './output/app_data/jobs/continuous/Quotebot' # the last folder name will become the webjob name in the portal
  ZIP_FILE: 'webjob.zip'
  ZIP_PATH: './output'
  ZIP_FILEPATH: './output/webjob.zip'
  SLN_PATH: './src/Quotebot.sln'
# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Version
        shell: pwsh
        run: |
          $version = "1.0.$([System.DateTime]::Now.ToString('yyMM')).$($Env:GITHUB_RUN_NUMBER)$($Env:GITHUB_RUN_ATTEMPT)"
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          Write-Host $version
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: dotnet build
        run: dotnet build ${{ENV.SLN_PATH}} --configuration Release -p:Version=${{ENV.BUILD_VERSION}} --output ${{env.BINARIES}}
      
      - name: Create Release Artifact
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ${{ENV.ZIP_FILE}}
          directory: ${{ENV.ZIP_PATH}}
          exclusions: 'Quotebot.exe app_data/**/unix/*'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: quotebot-artifact
          path: ${{ENV.ZIP_FILEPATH}}
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'      
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: quotebot-artifact
      - name: Publish WebJob
        uses: srijken/azure-webjob-deploy@master
        with: 
          zip-file: ${{ENV.ZIP_FILE}}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_59E93C47D0E84C97A2528BC20F84FB38 }}