name: Docker Build and Deploy

on:
  push:
    branches:
      # - 'main'
      - '**'

env:
  SLN_PATH: './src/Quotebot.sln'
  BINARIES: './output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Generate Version
        shell: pwsh
        run: |
          $version = "1.0.$([System.DateTime]::Now.ToString('yyMM')).$([System.DateTime]::Now.ToString('dd'))$($Env:GITHUB_RUN_NUMBER)$($Env:GITHUB_RUN_ATTEMPT)"
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          Write-Host $version

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: dotnet build
        run: dotnet build ${{ENV.SLN_PATH}} --configuration Release -p:Version=${{ENV.BUILD_VERSION}} --output ${{env.BINARIES}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Test Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          build-args: |
            source=${{env.BINARIES}}
          push: false
          load: true
          tags: quotemage:test
      
      - name: Test Container
        run: |
          docker run --rm quotemage:test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: quotebot-artifact
          path: |
            ${{env.BINARIES}}
            !${{env.BINARIES}}/appruntimes_data/win**/**
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'      
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: quotebot-artifact
          path: ${{env.BINARIES}}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Release Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          build-args: |
            source=${{env.BINARIES}}
          push: false
          tags: quotemage:${{ env.BUILD_VERSION }}

      

      