on:
  push:
    branches:
      # - 'main'
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Generate Version
        shell: pwsh
        run: |
          $version = "1.0.$([System.DateTime]::Now.ToString('yyMM')).$([System.DateTime]::Now.ToString('dd'))$($Env:GITHUB_RUN_ID)"
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          Write-Host $version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          push: false
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          tags: quotemage:${{ env.BUILD_VERSION }}

      