name: Scale Container

on:
  workflow_dispatch:
    inputs:
      minReplicas:
        description: Scale Container. Pick either 0 or 1
        required: true
        type: number
        default: 1
      containerVersion:
        description: Version of container to scale.
        required: true

permissions:
  id-token: write # Required for requesting the JWT

jobs:
  Scale:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Echo Parameters
        run: |
          echo "container-version: + ${{ github.event.inputs.containerVersion }}"
          echo "min-replicas: ${{ github.event.inputs.minReplicas }}"
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_GITHUB_ACTION_QUOTEBOT_APP }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_GITHUB_ACTION_QUOTEBOT_APP }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: CoNerd
          template: ./container-app.json
          deploymentName: MageBot-Scale-${{ github.event.inputs.containerVersion }}
          parameters: min-replicas=${{ github.event.inputs.minReplicas }} container-version=${{ github.event.inputs.containerVersion }} conerdazurecrio-conerd-pwd=${{ secrets.CONTAINER_REGISTRY_PASSWORD }} keyvault-api-clientid=${{ secrets.KEYVAULT_CLIENTID }} keyvault-api-secret=${{ secrets.KEYVAULT_SECRET }} keyvault-secret-url=${{ secrets.KEYVAULT_URI }}
